# .pre-commit-config.yaml for a Guix repository

# Optional: enforce minimum version of pre-commit
minimum_pre_commit_version: '2.0.0'

default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # make sure to pick a stable tag
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args:
          - --maxkb=2000
